import fs from 'fs';
import path from 'path';

let tagNames = ["Action",
"Casual",
"Bullet Hell",
"Arena Shooter",
"Sci-fi",
"Medieval",
"War",
"Shoot 'Em Up",
"Survival",
"Surreal",
"Action-Adventure",
"PvE",
"Top-Down",
"Combat",
"RPG",
"Action Roguelike",
"Roguelike",
"Roguelite",
"Sexual Content",
"Mature",
"Hentai",
"Nudity",
"NSFW",
"JRPG",
"FMV",
"Visual Novel",
"Zombies",
"Simulation",
"Adventure",
"Survival Horror",
"2D",
"Dating Sim",
"Anime",
"Choose Your Own Adventure",
"Immersive Sim",
"Atmospheric",
"Board Game",
"Deckbuilding",
"Physics",
"3D",
"Choices Matter",
"Stylized",
"Dark Fantasy",
"Strategy",
"Card Battler",
"Point & Click",
"Trading Card Game",
"Minimalist",
"Noir",
"Dark",
"Mythology",
"Gambling",
"Tabletop",
"Traditional Roguelike",
"Magic",
"Procedural Generation",
"Retro",
"1990's",
"Turn-Based Strategy",
"Character Customization",
"Turn-Based Combat",
"Tactical RPG",
"Pixel Graphics",
"Fantasy",
"Old School",
"Indie",
"Female Protagonist",
"Detective",
"Colorful",
"Crime",
"Cyberpunk",
"Futuristic",
"Investigation",
"Horror",
"Perma Death",
"Team-Based",
"Psychological Horror",
"Exploration",
"Time Management",
"First-Person",
"Funny",
"Demons",
"Difficult",
"Dark Humor",
"Precision Platformer",
"Story Rich",
"Narration",
"Puzzle Platformer",
"Racing",
"Platformer",
"Third Person",
"Philosophical",
"3D Platformer",
"Replay Value",
"Linear",
"RTS",
"Wargame",
"Isometric",
"Resource Management",
"Base Building",
"City Builder",
"Tactical",
"Real Time Tactics",
"Military",
"Historical",
"Puzzle",
"Collectathon",
"Creature Collector",
"Hidden Object",
"Hand-drawn",
"Cute",
"Nature",
"Family Friendly",
"Relaxing",
"Comedy",
"Multiple Endings",
"Walking Simulator",
"Narrative",
"Satire",
"Mystery",
"Game Development",
"Life Sim",
"Idler",
"Gothic",
"LGBTQ+",
"Sandbox",
"Building",
"Management",
"Cartoony",
"Crafting",
"Sports",
"Basketball",
"Text-Based",
"Dice",
"Dystopian ",
"Artificial Intelligence",
"Interactive Fiction",
"Space",
"Conversation",
"Action RPG",
"Steampunk",
"Stealth",
"Robots",
"Emotional",
"Clicker",
"Economy",
"Colony Sim",
"Open World",
"Violent",
"Gore",
"Farming Sim",
"Experimental",
"Dungeon Crawler",
"Souls-like",
"Fishing",
"Inventory Management",
"Loot",
"Grand Strategy",
"4X",
"Moddable",
"Turn-Based",
"Diplomacy",
"Hex Grid",
"Cats",
"Wholesome",
"Cozy",
"Score Attack",
"Time Attack",
"Top-Down Shooter",
"Sailing",
"Battle Royale",
"Naval Combat",
"Naval",
"Pirates",
"Time Travel",
"1980s",
"Arcade",
"Boss Rush",
"Mechs",
"Gun Customization",
"Thriller",
"Parody ",
"2D Platformer",
"Metroidvania",
"Side Scroller",
"2.5D",
"Post-apocalyptic",
"Transhumanism",
"Electronic Music",
"Dark Comedy",
"Psychedelic",
"Underground",
"Education",
"Typing",
"Short",
"Supernatural",
"Trading",
"Capitalism",
"Realistic",
"2D Fighter",
"Beat 'em up",
"Fighting",
"Level Editor",
"Vampire",
"Shooter",
"Fast-Paced",
"Hacking",
"Tower Defense",
"Roguelike Deckbuilder",
"Card Game",
"Superhero",
"Political",
"Politics",
"Comic Book",
"Political Sim",
"Strategy RPG",
"Sequel",
"Third-Person Shooter",
"World War II",
"Sniper",
"Lovecraftian",
"Turn-Based Tactics",
"Cinematic",
"Touch-Friendly",
"Tutorial",
"Destruction",
"Hack and Slash",
"Dog",
"Competitive",
"Cooking",
"Boxing",
"3D Fighter",
"Auto Battler",
"Automation",
"Memes",
"Drama",
"CRPG",
"Logic",
"Romance",
"Modern",
"Runner",
"Party Game",
"Flight",
"Jet",
"Time Manipulation",
"Extraction Shooter",
"Aliens",
"FPS",
"Class-Based",
"Dinosaurs",
"Action RTS",
"Vehicular Combat",
"Utilities",
"Music",
"Party-Based RPG",
"Cartoon",
"Driving",
"Transportation",
"Automobile Sim",
"Psychological",
"World War I",
"Swordplay",
"Hero Shooter",
"Conspiracy",
"Dragons",
"Space Sim",
"3D Vision",
"Word Game",
"Spectacle fighter",
"Trains",
"Voxel",
"Parkour",
"Open World Survival Craft",
"Combat Racing",
"America",
"Martial Arts",
"Wrestling",
"Ninja",
"Science",
"Farming",
"Grid-Based Movement",
"Abstract",
"Programming",
"God Game",
"Otome",
"Dynamic Narration",
"RPGMaker",
"Hunting",
"Episodic",
"Social Deduction",
"Jump Scare",
"Lore-Rich",
"Immersive",
"Snow",
"Rhythm",
"Music-Based Procedural Generation",
"Mining",
"Agriculture",
"Foreign",
"Trivia",
"Quick-Time Events",
"Looter Shooter",
"Character Action Game",
"Nonlinear",
"Real-Time with Pause",
"Real-Time",
"Spelling",
"Web Publishing",
"Underwater",
"Escape Room",
"BMX",
"Cycling",
"Faith",
"Job Simulator",
"Party",
"Shop Keeper",
"Boomer Shooter",
"Villain Protagonist",
"Birds",
"Assassin",
"Minigames",
"Sokoban",
"Mystery Dungeon",
"Skiing",
"Outbreak Sim",
"Skateboarding",
"Skating",
"Mouse only",
"Bullet Time",
"MOBA",
"Mahjong",
"Coding",
"Software",
"Design & Illustration",
"Alternate History",
"Western",
"Spaceships",
"Medical Sim",
"Musou",
"Football (American)",
"eSports",
"TrackIR",
"Werewolves",
"Match 3",
"Rome",
"Hobby Sim",
"6DOF",
"Tanks",
"Pool",
"Heist",
"Dungeons & Dragons",
"Dwarf",
"Offroad",
"Solitaire",
"Twin Stick Shooter",
"Submarine",
"Illuminati",
"Bowling",
"Movie",
"Hockey",
"LEGO",
"Horses",
"On-Rails Shooter",
"Football (Soccer)",
"Cold War",
"Software Training",
"Audio Production",
"Rock Music",
"Animation & Modeling",
"Photo Editing",
"Archery",
"Elf",
"Blood",
"Chess",
"Experience",
"Mars",
"Unforgiving",
"Beautiful",
"Pinball",
"Bikes",
"360 Video",
"Instrumental Music",
"Roguevania",
"Snowboarding",
"Tile-Matching",
"Motorbike",
"Nostalgia",
"Ambient",
"Golf",
"Mini Golf",
"Warhammer 40K",
"Remake",
"Gaming",
"Tennis",
"Mod",
"Baseball",
"Vikings",
"ATV",
"Voice Control",
"Epic",
"Games Workshop",
"Intentionally Awkward Controls",
"Silent Protagonist",
"GameMaker",
"Benchmark",
"Fox",
"Volleyball",
"Video Production",
"Lemmings",
"Electronic",
"8-bit Music",
"Motocross",
"Rugby",
"Based On A Novel",
"Cricket",
"Hardware",
"Documentary",
"Steam Machine",
"Reboot",
"Feature Film",
"Snooker"
]
function createTagnameArray(tagNames){
    let tagnameArray = [];
    for (let i = 0; i < tagNames.length; i++) {
        tagnameArray.push([tagNames[i], i])
    }
    return tagnameArray
}

async function saveDataToJson() {
    try {
        const data = createTagnameArray(tagNames); // Fetch processed data
        const jsPath = path.join(process.cwd(), 'tags.js'); // Use process.cwd() for the current working directory

        console.log(`Saving data to: ${jsPath}`); // Log the path for debugging

        const jsContent = `export const tagNamesVariables = ${JSON.stringify(data, null, 2)};`;

        fs.writeFileSync(jsPath, jsContent); // Write jsdata to file
        console.log(`Data successfully written to ${jsPath}`);
        
    } catch (error) {
        console.error("Error saving data:", error);
    }
}


saveDataToJson();